# Generated by Django 2.1.7 on 2019-04-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRLapp', '0002_blackpoints_messages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
